# Generated by Django 5.2.9 on 2026-05-30 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='company',
            name='error_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='number_of_licences',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='error_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='number_of_licences',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='device_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DevicePendingApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uuid', models.CharField(max_length=255)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_approvals_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_pending_approval',
                'indexes': [models.Index(fields=['user', 'status'], name='device_pend_user_id_15cc21_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserApprovedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uuid', models.CharField(db_index=True, max_length=255)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices_approved', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_approved_device',
                'indexes': [models.Index(fields=['user', 'device_uuid', 'is_revoked'], name='user_approv_user_id_0f4a6e_idx')],
                'unique_together': {('user', 'device_uuid')},
            },
        ),
    ]
