# Generated by Django 5.2.9 on 2025-12-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
    ]
