# Generated by Django 5.2.9 on 2025-12-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0002_alter_company_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, default='user', max_length=32, null=True),
        ),
    ]
