# Generated by Django 5.2.9 on 2026-05-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0002_add_license_fields_device_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='refresh_jti',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
