# Generated by Django 5.2.9 on 2025-12-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='authentication_status',
            field=models.CharField(blank=True, default='waiting-for-response', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TransactionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(blank=True, max_length=20, null=True)),
                ('device_id', models.CharField(blank=True, max_length=20, null=True)),
                ('trip_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ticket_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ticket_date', models.DateField(blank=True, null=True)),
                ('ticket_time', models.TimeField(blank=True, null=True)),
                ('from_stage', models.IntegerField(blank=True, null=True)),
                ('to_stage', models.IntegerField(blank=True, null=True)),
                ('full_count', models.IntegerField(default=0)),
                ('half_count', models.IntegerField(default=0)),
                ('st_count', models.IntegerField(default=0)),
                ('phy_count', models.IntegerField(default=0)),
                ('lugg_count', models.IntegerField(default=0)),
                ('ticket_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lugg_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ticket_type', models.CharField(blank=True, max_length=10, null=True)),
                ('adjust_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pass_id', models.CharField(blank=True, max_length=20, null=True)),
                ('warrant_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_status', models.CharField(blank=True, max_length=5, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ladies_count', models.IntegerField(default=0)),
                ('senior_count', models.IntegerField(default=0)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ticket_status', models.CharField(blank=True, max_length=10, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('company_code', models.CharField(blank=True, max_length=10, null=True)),
                ('raw_payload', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transaction_data',
                'indexes': [models.Index(fields=['device_id', 'ticket_date'], name='transaction_device__54f2f9_idx'), models.Index(fields=['company_code'], name='transaction_company_1f9985_idx')],
            },
        ),
    ]
