# Generated by Django 5.2.9 on 2025-12-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0004_alter_company_authentication_status_transactiondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='authentication_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
