# Generated by Django 5.2.9 on 2025-12-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0005_alter_company_authentication_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transactiondata',
            constraint=models.UniqueConstraint(fields=('device_id', 'trip_number', 'ticket_number', 'ticket_date', 'ticket_time'), name='uniq_device_trip_ticket_datetime'),
        ),
    ]
