# Generated by Django 5.2.9 on 2025-12-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0006_transactiondata_uniq_device_trip_ticket_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='branch_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='device_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='project_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='authentication_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approve', 'Approved'), ('Expired', 'Expired'), ('Block', 'Blocked')], default='Pending', max_length=20, null=True),
        ),
    ]
