# Generated by Django 5.2.9 on 2025-12-26 09:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0007_alter_company_options_company_branch_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='authentication_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Validating', 'Validating'), ('Approve', 'Approved'), ('Expired', 'Expired'), ('Block', 'Blocked')], default='Pending', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TripCloseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palmtec_id', models.CharField(db_index=True, help_text='Device identifier (PalmtecID)', max_length=50)),
                ('company_code', models.CharField(help_text='Company code', max_length=100)),
                ('schedule', models.IntegerField(help_text='Schedule number')),
                ('trip_no', models.IntegerField(help_text='Trip number')),
                ('route_code', models.CharField(db_index=True, help_text='Route code', max_length=50)),
                ('up_down_trip', models.CharField(help_text='Trip direction indicator (U/D)', max_length=1)),
                ('start_datetime', models.DateTimeField(db_index=True, help_text='Trip start date and time')),
                ('end_datetime', models.DateTimeField(help_text='Trip end date and time')),
                ('start_ticket_no', models.BigIntegerField(help_text='Starting ticket number (lSTicketNo)')),
                ('end_ticket_no', models.BigIntegerField(help_text='Ending ticket number (lETicketNo)')),
                ('full_count', models.IntegerField(default=0, help_text='Full fare passengers (sFull + uFull)', validators=[django.core.validators.MinValueValidator(0)])),
                ('half_count', models.IntegerField(default=0, help_text='Half fare passengers (sHalf + uChild)', validators=[django.core.validators.MinValueValidator(0)])),
                ('st1_count', models.IntegerField(default=0, help_text='ST1 type passengers (sST1 + uSTCount)', validators=[django.core.validators.MinValueValidator(0)])),
                ('luggage_count', models.IntegerField(default=0, help_text='Luggage count (sLugg + uLugg)', validators=[django.core.validators.MinValueValidator(0)])),
                ('physical_count', models.IntegerField(default=0, help_text='Physical handicap passengers (sPhy + uPhy)', validators=[django.core.validators.MinValueValidator(0)])),
                ('pass_count', models.IntegerField(default=0, help_text='Pass holders (sPass)', validators=[django.core.validators.MinValueValidator(0)])),
                ('ladies_count', models.IntegerField(default=0, help_text='Ladies passengers (sLadies + uLadies)', validators=[django.core.validators.MinValueValidator(0)])),
                ('senior_count', models.IntegerField(default=0, help_text='Senior citizen passengers (sSenior + uSenior)', validators=[django.core.validators.MinValueValidator(0)])),
                ('full_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Full fare collection (fFullColl + uFullColl)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('half_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Half fare collection (fHalfColl + uChildColl)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('st_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='ST collection (fSTColl + uSTColl)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('luggage_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Luggage collection (fLuggageColl + uLuggColl)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('physical_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Physical handicap collection (fPhyColl + uPhyColl)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ladies_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ladies collection (fLadiColl + uLadiesColl)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('senior_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Senior collection (fSeniorColl + uSeniorColl)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('adjust_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Adjustment collection (fAdjustColl) - can be negative', max_digits=10)),
                ('expense_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expense amount (fExpenseAmount)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total collection (fTotalColl)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('upi_ticket_count', models.IntegerField(default=0, help_text='UPI ticket count (sUpiTicketCount)', validators=[django.core.validators.MinValueValidator(0)])),
                ('upi_ticket_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='UPI ticket amount (fUPITicketAmount)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When server received this data')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
            ],
            options={
                'verbose_name': 'Trip Close Data',
                'verbose_name_plural': 'Trip Close Datas',
                'db_table': 'trip_close_data',
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['palmtec_id', 'start_datetime'], name='trip_close__palmtec_55e486_idx'), models.Index(fields=['route_code', 'start_datetime'], name='trip_close__route_c_64c498_idx'), models.Index(fields=['start_datetime'], name='trip_close__start_d_231892_idx')],
                'unique_together': {('palmtec_id', 'schedule', 'trip_no', 'start_datetime')},
            },
        ),
    ]
