# Generated by Django 5.2.9 on 2025-12-31 05:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0009_company_created_by_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='MosambeeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_status', models.CharField(choices=[('RECEIVED', 'Received'), ('VALIDATING', 'Validating'), ('VALIDATED', 'Validated'), ('VALIDATION_FAILED', 'Validation Failed'), ('RECONCILING', 'Reconciling'), ('PENDING_VERIFICATION', 'Pending Verification'), ('FAILED', 'Failed')], db_index=True, default='RECEIVED', max_length=30)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged for Review'), ('DISPUTED', 'Disputed')], db_index=True, default='UNVERIFIED', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('checksum_received', models.CharField(max_length=512)),
                ('checksum_calculated', models.CharField(blank=True, max_length=512, null=True)),
                ('is_checksum_valid', models.BooleanField(db_index=True, default=False)),
                ('validation_error', models.TextField(blank=True, null=True)),
                ('reconciliation_status', models.CharField(choices=[('PENDING', 'Pending'), ('AUTO_MATCHED', 'Auto-Matched'), ('AMOUNT_MISMATCH', 'Amount Mismatch'), ('NOT_FOUND', 'Ticket Not Found'), ('DUPLICATE', 'Duplicate Payment'), ('MANUAL_MATCH', 'Manually Matched')], db_index=True, default='PENDING', max_length=20)),
                ('reconciliation_error', models.TextField(blank=True, null=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('settlement_batch_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('settlement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('repost_count', models.IntegerField(default=0)),
                ('first_received_at', models.DateTimeField(auto_now_add=True)),
                ('last_received_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=45)),
                ('merchantId', models.CharField(db_index=True, max_length=45)),
                ('businessName', models.CharField(blank=True, max_length=100, null=True)),
                ('addressLine1', models.CharField(blank=True, max_length=255, null=True)),
                ('addressLine2', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_date', models.DateField(db_index=True)),
                ('transaction_time', models.TimeField()),
                ('transaction_datetime', models.DateTimeField(db_index=True)),
                ('transactionLat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('transactionLong', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('transactionSTAN', models.CharField(blank=True, max_length=6, null=True)),
                ('transactionRRN', models.CharField(db_index=True, max_length=50)),
                ('transactionID', models.BigIntegerField(db_index=True, unique=True)),
                ('tgTransactionId', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('transactionAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cashBack', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tipAmount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('responseCode', models.CharField(db_index=True, max_length=6)),
                ('transactionStatus', models.CharField(max_length=100)),
                ('transactionAuthCode', models.CharField(blank=True, max_length=60, null=True)),
                ('transactionCardNumber', models.CharField(max_length=16)),
                ('cardHolderName', models.CharField(blank=True, max_length=150, null=True)),
                ('cardType', models.CharField(max_length=45)),
                ('creditDebitCardType', models.CharField(blank=True, max_length=15, null=True)),
                ('transactionTerminalId', models.CharField(db_index=True, max_length=20)),
                ('transactionBatchNumber', models.IntegerField(blank=True, null=True)),
                ('appVersion', models.CharField(blank=True, max_length=10, null=True)),
                ('invoiceNumber', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('billNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('refTxnId', models.CharField(blank=True, max_length=45, null=True)),
                ('transactionTypeId', models.IntegerField()),
                ('transactionTypeName', models.CharField(blank=True, max_length=25, null=True)),
                ('currencyId', models.CharField(max_length=5)),
                ('acquirerName', models.CharField(max_length=50)),
                ('narration', models.CharField(blank=True, max_length=100, null=True)),
                ('aid', models.CharField(blank=True, max_length=50, null=True)),
                ('ici', models.CharField(blank=True, max_length=5, null=True)),
                ('apn', models.CharField(blank=True, max_length=55, null=True)),
                ('appLabel', models.CharField(blank=True, max_length=60, null=True)),
                ('tvr', models.CharField(blank=True, max_length=10, null=True)),
                ('tsi', models.CharField(blank=True, max_length=4, null=True)),
                ('ac', models.CharField(blank=True, max_length=20, null=True)),
                ('cid', models.CharField(blank=True, max_length=2, null=True)),
                ('cvm', models.CharField(blank=True, max_length=6, null=True)),
                ('tipProcessing', models.BooleanField(default=False)),
                ('transactionMode', models.CharField(blank=True, max_length=10, null=True)),
                ('MsrAndPinVerification', models.BooleanField(default=False)),
                ('raw_request_data', models.JSONField()),
                ('response_sent_to_mosambee', models.JSONField(blank=True, null=True)),
                ('manager_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mosambee Payment Transaction',
                'verbose_name_plural': 'Mosambee Payment Transactions',
                'db_table': 'mosambee_transaction',
                'ordering': ['-transaction_datetime'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='TicketAppB.company'),
        ),
        migrations.AddIndex(
            model_name='tripclosedata',
            index=models.Index(fields=['company_code'], name='trip_close__company_bfdcec_idx'),
        ),
        migrations.AddField(
            model_name='mosambeetransaction',
            name='manually_reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manually_reconciled_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mosambeetransaction',
            name='related_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='TicketAppB.transactiondata'),
        ),
        migrations.AddField(
            model_name='mosambeetransaction',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_mosambee_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mosambeetransaction',
            index=models.Index(fields=['transaction_date'], name='mosambee_tr_transac_8ac57b_idx'),
        ),
        migrations.AddIndex(
            model_name='mosambeetransaction',
            index=models.Index(fields=['-transaction_datetime'], name='mosambee_tr_transac_f1268a_idx'),
        ),
        migrations.AddIndex(
            model_name='mosambeetransaction',
            index=models.Index(fields=['verification_status', 'transaction_date'], name='mosambee_tr_verific_3ac527_idx'),
        ),
        migrations.AddIndex(
            model_name='mosambeetransaction',
            index=models.Index(fields=['verification_status', 'merchantId'], name='mosambee_tr_verific_2658ef_idx'),
        ),
        migrations.AddIndex(
            model_name='mosambeetransaction',
            index=models.Index(fields=['processing_status', 'transaction_date'], name='mosambee_tr_process_fe94ad_idx'),
        ),
        migrations.AddIndex(
            model_name='mosambeetransaction',
            index=models.Index(fields=['reconciliation_status'], name='mosambee_tr_reconci_678a3f_idx'),
        ),
        migrations.AddIndex(
            model_name='mosambeetransaction',
            index=models.Index(fields=['invoiceNumber'], name='mosambee_tr_invoice_de5ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='mosambeetransaction',
            index=models.Index(fields=['transactionRRN'], name='mosambee_tr_transac_492061_idx'),
        ),
        migrations.AddIndex(
            model_name='mosambeetransaction',
            index=models.Index(fields=['settlement_batch_id'], name='mosambee_tr_settlem_2f9560_idx'),
        ),
        migrations.AddIndex(
            model_name='mosambeetransaction',
            index=models.Index(fields=['merchantId', 'transaction_date'], name='mosambee_tr_merchan_8016e3_idx'),
        ),
        migrations.AddIndex(
            model_name='mosambeetransaction',
            index=models.Index(fields=['responseCode', 'transaction_date'], name='mosambee_tr_respons_5d7729_idx'),
        ),
        migrations.AddIndex(
            model_name='mosambeetransaction',
            index=models.Index(fields=['is_checksum_valid', 'processing_status'], name='mosambee_tr_is_chec_10302f_idx'),
        ),
        migrations.AddIndex(
            model_name='mosambeetransaction',
            index=models.Index(fields=['transactionTerminalId', 'transaction_date'], name='mosambee_tr_transac_89e4a6_idx'),
        ),
    ]
