# Generated by Django 5.2.9 on 2026-01-05 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0010_mosambeetransaction_alter_customuser_company_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transactiondata',
            new_name='transaction_company_ea2cd3_idx',
            old_name='transaction_company_1f9985_idx',
        ),
        migrations.AlterField(
            model_name='company',
            name='number_of_licence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='company_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='TicketAppB.company'),
        ),
    ]
