# Generated by Django 5.2.9 on 2026-01-06 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0011_rename_transaction_company_1f9985_idx_transaction_company_ea2cd3_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tripclosedata',
            new_name='trip_close__company_992f33_idx',
            old_name='trip_close__company_bfdcec_idx',
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='company_code',
            field=models.ForeignKey(blank=True, help_text='Company code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='TicketAppB.company'),
        ),
    ]
