# Generated by Django 5.2.9 on 2026-01-06 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0012_rename_trip_close__company_bfdcec_idx_trip_close__company_992f33_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondata',
            name='branch_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='TicketAppB.branch'),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='total_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='ticket_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Cash'), (1, 'UPI')], default=0, null=True),
        ),
        migrations.AddIndex(
            model_name='transactiondata',
            index=models.Index(fields=['branch_code'], name='transaction_branch__59630b_idx'),
        ),
    ]
