# Generated by Django 5.2.9 on 2026-01-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0013_transactiondata_branch_code_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transactiondata',
            index=models.Index(fields=['total_tickets', 'ticket_date'], name='transaction_total_t_4ffd2e_idx'),
        ),
    ]
