# Generated by Django 5.2.9 on 2026-01-09 07:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0014_transactiondata_transaction_total_t_4ffd2e_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transactiondata',
            name='transaction_total_t_4ffd2e_idx',
        ),
        migrations.AddField(
            model_name='tripclosedata',
            name='branch_code',
            field=models.ForeignKey(blank=True, help_text='Branch code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_closes', to='TicketAppB.branch'),
        ),
        migrations.AddField(
            model_name='tripclosedata',
            name='end_date',
            field=models.DateField(blank=True, help_text='Trip end date (extracted from end_datetime)', null=True),
        ),
        migrations.AddField(
            model_name='tripclosedata',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Trip end time (extracted from end_datetime)', null=True),
        ),
        migrations.AddField(
            model_name='tripclosedata',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, help_text='Trip start date (extracted from start_datetime)', null=True),
        ),
        migrations.AddField(
            model_name='tripclosedata',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Trip start time (extracted from start_datetime)', null=True),
        ),
        migrations.AddField(
            model_name='tripclosedata',
            name='total_cash_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cash collection (total_collection - upi_ticket_amount)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='tripclosedata',
            name='total_cash_tickets',
            field=models.IntegerField(default=0, help_text='Total cash tickets (total_tickets - upi_ticket_count)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tripclosedata',
            name='total_tickets',
            field=models.IntegerField(default=0, help_text='Total tickets issued (sum of all counts including pass)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='tripclosedata',
            index=models.Index(fields=['start_date'], name='trip_close__start_d_d76b29_idx'),
        ),
        migrations.AddIndex(
            model_name='tripclosedata',
            index=models.Index(fields=['company_code', 'start_date'], name='trip_close__company_6e53ba_idx'),
        ),
        migrations.AddIndex(
            model_name='tripclosedata',
            index=models.Index(fields=['branch_code'], name='trip_close__branch__a056eb_idx'),
        ),
    ]
