# Generated by Django 5.2.9 on 2026-01-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0015_remove_transactiondata_transaction_total_t_4ffd2e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosambeetransaction',
            name='processing_status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('VALIDATED', 'Validated'), ('VALIDATION_FAILED', 'Validation Failed'), ('RECONCILING', 'Reconciling'), ('PENDING_VERIFICATION', 'Pending Verification')], db_index=True, default='RECEIVED', max_length=30),
        ),
    ]
