# Generated by Django 5.2.9 on 2026-02-10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0018_rename_bus_type_company_3954e7_idx_mdb_bus_typ_company_2f110d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_code', models.CharField(max_length=50, unique=True)),
                ('dealer_name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dealer',
            },
        ),
        migrations.CreateModel(
            name='DealerCustomerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_mappings', to='TicketAppB.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_company_mappings_created', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_mappings', to='TicketAppB.dealer')),
            ],
            options={
                'db_table': 'dealer_customer_mapping',
                'unique_together': {('dealer', 'company')},
            },
        ),
        migrations.CreateModel(
            name='ExecutiveCompanyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_mappings', to='TicketAppB.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_company_mappings_created', to=settings.AUTH_USER_MODEL)),
                ('executive_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_company_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'executive_company_mapping',
                'unique_together': {('executive_user', 'company')},
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='TicketAppB.dealer'),
        ),
        migrations.AddIndex(
            model_name='dealer',
            index=models.Index(fields=['dealer_code'], name='dealer_dealer_code_idx'),
        ),
        migrations.AddIndex(
            model_name='dealer',
            index=models.Index(fields=['dealer_name'], name='dealer_dealer_name_idx'),
        ),
        migrations.AddIndex(
            model_name='dealer',
            index=models.Index(fields=['is_active'], name='dealer_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='dealercustomermapping',
            index=models.Index(fields=['dealer', 'company'], name='dcm_dealer_company_idx'),
        ),
        migrations.AddIndex(
            model_name='dealercustomermapping',
            index=models.Index(fields=['company'], name='dcm_company_idx'),
        ),
        migrations.AddIndex(
            model_name='dealercustomermapping',
            index=models.Index(fields=['is_active'], name='dcm_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='executivecompanymapping',
            index=models.Index(fields=['executive_user', 'company'], name='ecm_exec_company_idx'),
        ),
        migrations.AddIndex(
            model_name='executivecompanymapping',
            index=models.Index(fields=['company'], name='ecm_company_idx'),
        ),
        migrations.AddIndex(
            model_name='executivecompanymapping',
            index=models.Index(fields=['is_active'], name='ecm_is_active_idx'),
        ),
    ]
