# Generated by Django 5.2.4 on 2026-02-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TicketAppB", "0019_dealer_executive_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_device_valid",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="UserDeviceMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username_snapshot", models.CharField(max_length=150)),
                ("device_uid", models.CharField(max_length=255)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web_desktop", "Web Desktop"),
                            ("web_mobile", "Web Mobile"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("status", models.IntegerField(choices=[(0, "Pending"), (1, "Approved"), (2, "Inactive")], default=0)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_device_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_device_mapping",
            },
        ),
        migrations.AddConstraint(
            model_name="userdevicemapping",
            constraint=models.UniqueConstraint(fields=("user", "device_uid"), name="uniq_user_device_uid"),
        ),
        migrations.AddIndex(
            model_name="userdevicemapping",
            index=models.Index(fields=["user", "status"], name="user_device__user_id_ce2ca4_idx"),
        ),
        migrations.AddIndex(
            model_name="userdevicemapping",
            index=models.Index(fields=["device_uid"], name="user_device__device__f60cbe_idx"),
        ),
    ]
