# Generated by Django 5.2.4 on 2026-02-11

import secrets
from django.db import migrations, models


def dedupe_device_uids(apps, schema_editor):
    UserDeviceMapping = apps.get_model("TicketAppB", "UserDeviceMapping")
    db_alias = schema_editor.connection.alias

    duplicate_uids = (
        UserDeviceMapping.objects.using(db_alias)
        .values("device_uid")
        .annotate(row_count=models.Count("id"))
        .filter(row_count__gt=1)
    )

    for duplicate in duplicate_uids:
        uid = duplicate["device_uid"]
        mappings = list(
            UserDeviceMapping.objects.using(db_alias)
            .filter(device_uid=uid)
            .order_by("status", "created_at", "id")
        )
        keeper = mappings[0]
        for mapping in mappings[1:]:
            new_uid = secrets.token_urlsafe(24)
            while UserDeviceMapping.objects.using(db_alias).filter(device_uid=new_uid).exists():
                new_uid = secrets.token_urlsafe(24)
            mapping.status = 2  # INACTIVE
            mapping.device_uid = new_uid
            mapping.save(update_fields=["status", "device_uid", "updated_at"])
        keeper.save(update_fields=["updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("TicketAppB", "0020_customuser_is_device_valid_user_device_mapping"),
    ]

    operations = [
        migrations.RunPython(dedupe_device_uids, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="userdevicemapping",
            name="uniq_user_device_uid",
        ),
        migrations.AddConstraint(
            model_name="userdevicemapping",
            constraint=models.UniqueConstraint(fields=("device_uid",), name="uniq_global_device_uid"),
        ),
    ]
