# Generated by Django 5.2.9 on 2026-02-11 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0021_device_uid_global_unique'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dealer',
            new_name='dealer_dealer__a85211_idx',
            old_name='dealer_dealer_code_idx',
        ),
        migrations.RenameIndex(
            model_name='dealer',
            new_name='dealer_dealer__3f34ff_idx',
            old_name='dealer_dealer_name_idx',
        ),
        migrations.RenameIndex(
            model_name='dealer',
            new_name='dealer_is_acti_7aa802_idx',
            old_name='dealer_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='dealercustomermapping',
            new_name='dealer_cust_dealer__088900_idx',
            old_name='dcm_dealer_company_idx',
        ),
        migrations.RenameIndex(
            model_name='dealercustomermapping',
            new_name='dealer_cust_company_83e1d1_idx',
            old_name='dcm_company_idx',
        ),
        migrations.RenameIndex(
            model_name='dealercustomermapping',
            new_name='dealer_cust_is_acti_a472df_idx',
            old_name='dcm_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='executivecompanymapping',
            new_name='executive_c_executi_7c5cec_idx',
            old_name='ecm_exec_company_idx',
        ),
        migrations.RenameIndex(
            model_name='executivecompanymapping',
            new_name='executive_c_company_a6f371_idx',
            old_name='ecm_company_idx',
        ),
        migrations.RenameIndex(
            model_name='executivecompanymapping',
            new_name='executive_c_is_acti_f5e955_idx',
            old_name='ecm_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='userdevicemapping',
            new_name='user_device_user_id_3fdae7_idx',
            old_name='user_device__user_id_ce2ca4_idx',
        ),
        migrations.RenameIndex(
            model_name='userdevicemapping',
            new_name='user_device_device__7cff9f_idx',
            old_name='user_device__device__f60cbe_idx',
        ),
    ]
