# Generated by Django 5.2.9 on 2026-02-16 06:34

import TicketAppB.models.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0022_rename_dealer_dealer_code_idx_dealer_dealer__a85211_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', TicketAppB.models.managers.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='project_code',
        ),
        migrations.AddField(
            model_name='company',
            name='mobile_device_count',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='branch_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='device_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
