# Generated by Django 5.2.9 on 2026-02-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0023_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevicemapping',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
