# Generated by Django 5.2.9 on 2026-02-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0024_userdevicemapping_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fare',
        ),
    ]
