# Generated by Django 5.2.9 on 2026-02-17 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0025_delete_fare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, unique=True)),
                ('row', models.IntegerField(default=0)),
                ('col', models.IntegerField(default=0)),
                ('fare_amount', models.IntegerField(default=0)),
                ('route_name', models.CharField(blank=True, help_text='Denormalized route name snapshot', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='TicketAppB.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fares_created', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='TicketAppB.route')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fares_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mdb_fare',
                'indexes': [models.Index(fields=['route', 'row', 'col'], name='mdb_fare_route_i_28061d_idx'), models.Index(fields=['company'], name='mdb_fare_company_729e9a_idx')],
                'unique_together': {('route', 'row', 'col')},
            },
        ),
    ]
