# Generated by Django 5.2.9 on 2026-02-24 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0026_fare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depot_code', models.CharField(max_length=50, unique=True)),
                ('depot_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'depot',
            },
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='branch',
            name='company',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transactiondata',
            name='branch_code',
        ),
        migrations.RemoveField(
            model_name='tripclosedata',
            name='branch_code',
        ),
        migrations.RemoveIndex(
            model_name='transactiondata',
            name='transaction_branch__59630b_idx',
        ),
        migrations.RemoveIndex(
            model_name='tripclosedata',
            name='trip_close__branch__a056eb_idx',
        ),
        migrations.AddField(
            model_name='depot',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='TicketAppB.company'),
        ),
        migrations.AddField(
            model_name='depot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depots_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='depot_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='TicketAppB.depot'),
        ),
        migrations.AddField(
            model_name='tripclosedata',
            name='depot_code',
            field=models.ForeignKey(blank=True, help_text='Depot code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_closes', to='TicketAppB.depot'),
        ),
        migrations.AddIndex(
            model_name='transactiondata',
            index=models.Index(fields=['depot_code'], name='transaction_depot_c_ec24c5_idx'),
        ),
        migrations.AddIndex(
            model_name='tripclosedata',
            index=models.Index(fields=['depot_code'], name='trip_close__depot_c_2464aa_idx'),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.AddIndex(
            model_name='depot',
            index=models.Index(fields=['company', 'depot_code'], name='depot_company_47abaf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='depot',
            unique_together={('company', 'depot_code')},
        ),
    ]
