# Generated by Django 5.2.9 on 2026-02-24 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0027_depot_alter_branch_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='branch_count',
            new_name='depot_count',
        ),
    ]
