# Generated by Django 5.2.9 on 2026-03-11 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0028_rename_branch_count_company_depot_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewassignment',
            name='cleaner',
            field=models.ForeignKey(blank=True, limit_choices_to={'emp_type__emp_type_name': 'Cleaner'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cleaner_assignments', to='TicketAppB.employee'),
        ),
        migrations.AlterField(
            model_name='crewassignment',
            name='conductor',
            field=models.ForeignKey(blank=True, limit_choices_to={'emp_type__emp_type_name': 'Conductor'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conductor_assignments', to='TicketAppB.employee'),
        ),
        migrations.AlterField(
            model_name='crewassignment',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'emp_type__emp_type_name': 'Driver'}, on_delete=django.db.models.deletion.PROTECT, related_name='driver_assignments', to='TicketAppB.employee'),
        ),
        migrations.CreateModel(
            name='RawDataLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_payload', models.TextField()),
                ('source', models.CharField(choices=[('transaction', 'Transaction'), ('trip_close', 'Trip Close')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('company_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_data', to='TicketAppB.company')),
            ],
            options={
                'db_table': 'raw_data_log',
                'indexes': [models.Index(fields=['status', 'received_at'], name='raw_data_lo_status_010551_idx')],
            },
        ),
    ]
