# Generated by Django 5.2.9 on 2026-03-12 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0029_alter_crewassignment_cleaner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routebustype',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_bus_types', to='TicketAppB.route'),
        ),
    ]
