# Generated by Django 5.2.9 on 2026-03-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0030_alter_routebustype_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdatalog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('duplicate', 'Duplicate'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
