# Generated by Django 5.2.9 on 2026-04-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0031_alter_rawdatalog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MosambeePayoutCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statementId', models.CharField(db_index=True, max_length=100, unique=True)),
                ('payoutAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('utrNumber', models.CharField(db_index=True, max_length=100)),
                ('payoutDate', models.DateTimeField()),
                ('payoutAccount', models.CharField(max_length=50)),
                ('payoutBank', models.CharField(max_length=100)),
                ('payoutStatus', models.CharField(max_length=50)),
                ('transactions', models.JSONField(default=list)),
                ('deductions', models.JSONField(default=list)),
                ('raw_request_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mosambee Payout Callback',
                'verbose_name_plural': 'Mosambee Payout Callbacks',
                'db_table': 'mosambee_payout_callback',
                'ordering': ['-created_at'],
            },
        ),
    ]
