# Generated by Django 5.2.9 on 2026-04-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0034_routedepot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='etmdevice',
            new_name='etm_device_serial__1b708e_idx',
            old_name='etm_dev_serial_idx',
        ),
        migrations.RenameIndex(
            model_name='etmdevice',
            new_name='etm_device_company_48e279_idx',
            old_name='etm_dev_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='etmdevice',
            new_name='etm_device_dealer__11abe4_idx',
            old_name='etm_dev_dealer_idx',
        ),
        migrations.RenameIndex(
            model_name='etmdevice',
            new_name='etm_device_licence_0e1c5c_idx',
            old_name='etm_dev_status_idx',
        ),
        migrations.AddField(
            model_name='dealer',
            name='allocated_device_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dealer',
            name='allocated_licence_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dealer',
            name='allocated_mobile_device_count',
            field=models.IntegerField(default=0),
        ),
    ]
