# Generated by Django 5.2.9 on 2026-04-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0037_settingsprofile'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transactiondata',
            name='uniq_device_trip_ticket_datetime',
        ),
        migrations.RemoveIndex(
            model_name='transactiondata',
            name='transaction_device__54f2f9_idx',
        ),
        migrations.RenameField(
            model_name='transactiondata',
            old_name='device_id',
            new_name='palmtec_id',
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='trip_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='transactiondata',
            index=models.Index(fields=['palmtec_id', 'ticket_date'], name='transaction_palmtec_6e6080_idx'),
        ),
        migrations.AddConstraint(
            model_name='transactiondata',
            constraint=models.UniqueConstraint(fields=('palmtec_id', 'trip_number', 'ticket_number', 'ticket_date', 'ticket_time'), name='uniq_device_trip_ticket_datetime'),
        ),
    ]
