# Generated by Django 5.2.9 on 2026-04-28 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0038_remove_transactiondata_uniq_device_trip_ticket_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetype',
            name='emp_type_code',
            field=models.CharField(blank=True, help_text='Employee type code (set by MDB import only)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inspectordetails',
            name='inspector',
            field=models.ForeignKey(limit_choices_to={'emp_type__emp_type_name__iexact': 'Inspector'}, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='TicketAppB.employee'),
        ),
    ]
